### ISSUE TITLE
MCA custom skins not working

### ISSUE THREAD

**Issue by Hunterballard** [WildBamaBoy/minecraft-comes-alive#1000]
I download a skin off skindex then edit the same one to be sleeping. Rename the 2 (ex bakerf14) then put one into my textures with the other skins and the other into the sleeping folder. They always end up looking all jumbled. I tried searching 64x32 skins on skindex and put the one I found in Minecraft but the same thing happens. Can someone help me, please?

**Comment by SolCourage** [comment]
I managed to figure this out. So MCA uses the 1.7 skin template so due to the changes to the 1.8 onward skin templates the 1.8 ones are incompatible. You need to get the 1.8 template and upload it into a 1.7 skin maker/editor I used the NovaSkin one and save the template it makes. You will notice that it is more compact then the 1.8 templates just like the ones in MCA. Then just rename them and put in the proper texture folders (default and sleeping) and you should be golden.

**Comment by SolCourage** [comment]
The problem seems to be that the blank space that the 1.8 templates have that the 1.7 ones don't, seem to mess with how the skin is being retrieved thus making it look jumbled.
