### ISSUE TITLE
MCA File is corrupt with Malware

### ISSUE THREAD

**Issue by DonovanPreech** [WildBamaBoy/minecraft-comes-alive#1065]
As my title says I can't acess the file on the site, I didn't know where to report it but thats whats happend

**Comment by Mariomm-marti** [comment]
Disable your antivirus, some JARs are detected as malware.

**Comment by Tsoccerguy3** [comment]
Marlomm , you probably mean well and there are bad AV programs out there , but disabling a systems AV is bad advice . If it's a false positive , the AV vender has to be made aware .

**Comment by C0rn3j** [comment]
Assuming Windows, uninstall whatever AV you installed and stick to using the default Windows Defender.

**Comment by smmmadden** [comment]
Tsoccerguy3 is correct.  Uninstalling an Antivirus Program because of personal bias is not a proper recommendation.  If there is a file being flagged as unsafe, you still have the option to "block" or "accept" the risk and continue with the download.    

First step is taking a screenshot of the message coming from your Antivirus and providing the screenshot, AV Name/Version to the site owner - in this case MCA.  The owner of the file may determine the AV is incorrect and advise you to contact that vendor.  Or, your computer could already be compromised with a virus and showing false/positives.
Second step is making sure you are using a paid version of an AV program.  There are too many free ones and not all of them are safe to use.  Windows Security or Windows Defender is not enough by itself.
Third and certainly not last, run periodic virus and malware scans to ensure your computer is not infected.

Viruses come in many forms from an actual destructive virus that corrupts and/or removes files from your computer to malware which maliciously changes browser pages and/or popup errors saying you have a virus when you don't (until you click on it to make it go away).  Using an Anti-Malware program along with an AntiVirus program together provides the best coverage for both scenarios.  This is coming from my 35+ years experience in the Computer field (hardware & software). Hope this helps!
