### ISSUE TITLE
No "Special" option available for any villagers

### ISSUE THREAD

**Issue by tuneintothis** [WildBamaBoy/minecraft-comes-alive#1232]
MCA Version: 1.12.2
Minecraft Version: 1.12.2
Other Mods: Baubles, JEI, Botania, Pam's Harvestcraft, Animania, Backpack, Bookshelf, Cooking for Blockheads, Farming for Blockheads, Dynamic Trees, Everyone Poops, Hunting Dimension, Nature's Compass, Serene Seasons.

I've searched it dozens of times now, and I can't find a duplicate of my problem or the answer. I have tried it with Guards and Clerics, both of which should have a "Special" dialog option under the other options. This option does not exist. I can't adopt, divorce, or hire villagers. I've tried removing and re-adding certain mods. I've tried restarting my game, restarting my computer then game, deleting the mod and re-installing. What am I doing wrong?

![Glitch](https://user-images.githubusercontent.com/57199118/67902847-5a5f4480-fb27-11e9-9094-75a22c80fe60.png)

**Comment by WildBamaBoy** [comment]
This was removed in MCA 6.0+

**Comment by pupco13** [comment]
This feature was removed? then how are you supposed to divorce villagers? theres no divorce papers either. 
if you mean this PROBLEM was removed then youre wrong. I'm playing the newest version for 1.12.2 (6.1.0) and I'm still having this issue. I've also reinstalled it and tried the mod without ANY other mods AND even tried other 1.12.2 versions the issue still exists. This post shouldn't be closed.
