### ISSUE TITLE
Add Small Quests

### ISSUE THREAD

**Issue by WildBamaBoy** [WildBamaBoy/minecraft-comes-alive#221]

**Comment by DemonicIntent** [comment]
Quests:
======
Item Quests:
 - Bring the Baker "X Amount" of Wheat, "X Amount" of Eggs = Earn Respect & Item (Cake, Bread, Etc.)
 - Bring the Blacksmith "X Amount" of Iron, Coal = Earn Respect & Rarely an Item

Travel Quests:
 - Start with a Guard, Walk around the Village at Night (Do the Guard's Patrol for a night.) - Earn Respect

Respect:
=======
Respect can be used for the Monarch System, your chances for wooing a villager into a relationship.  Or respect can influence how villagers talk to you.

**Comment by JoshuaDR** [comment]
How about some jobs like working as a Guard or farmer. Players can earn emeralds when doing it.

**Comment by Dextrositylight** [comment]
Been using the mod since 5.0 came out and I'm loving it, been checking that changelog each day since, exciting, especially since seeing some of the features being reworked in a youtube series, my suggestion in regards to this post would be a captain of the guard you could work for?
Or perhaps a knight if the monarch system is in place again? :)

**Comment by TheShootingStar45** [comment]
How about we can help each other friends in need? Add a small quest like some villagers would like a help, and then we can help them depending on their professions, like gathering seeds for farmers :smiley:

**Comment by DRULES679** [comment]
Once again, DemonicIntent comes up with the best idea ever. Keep it up! This update is gonna be the best one ever!

**Comment by WildBamaBoy** [comment]
Moved somewhere secret...
