### ISSUE TITLE
Hopes and Suggestions for 5.0.0 

### ISSUE THREAD

**Issue by Grimard** [WildBamaBoy/minecraft-comes-alive#240]
I have recently started playing with your mod, it is awsome to have functional NPCs in the game, I however thought it fell a little short in ability, now I understand you are rewriting the mod and would like to make some suggestions.

- expand the commands you can give miners, I was thinking maybe something along the lines of giving a user friendly interface to computer craft turtle functions, or something similar. IE: a box that you can click to switch from excavate to tunnel, and then some text boxes that allow players to specify co-ordinates, height, dimensions and direction of the tunnel or hole.

- allow users to specify the areas for gardens and tree chopping (so they don't tear up the front lawn or chop down a house).

- maybe add a feature so you can set re-occurring activities, such as have them actually tend the garden instead of just planting.  

- it would also be great to add support for third party weapon and armor mods such as tinkers construct, or add a configuration file where we can specify which items classify as weapons or armor.

- maybe add a leveling system so villagers can become more proficient at task and have more health with a configuration file to scale with mod packs.

**Comment by Razorskills** [comment]
I like these ideas.

**Comment by WildBamaBoy** [comment]
- (Expand the commands you can give miners.)
Mining is being reworked to include creating a predefined mine and gathering resources from it (slowly), or the old function where children would tell you where ores were.

- (Allow users to specify the areas for gardens and tree chopping.)
Already present (radius setting in the chore options) and will be returning.

- (Set re-occurring activities, such as have them actually tend the garden instead of just planting.)
This is already present in earlier versions of MCA - the farming chore's "maintain" mode.

- (Third party weapon support)
Since item IDs no longer exist, I do not know of a feasible way of doing this. Users will never figure out the appropriate names for items.

- (Leveling system for villagers)
What criteria should be used to determine whether or not they level up?

**Comment by Grimard** [comment]
- (Expand the commands you can give miners.) 
it would be great to see them actually be able to mine/collect resources in a useful way.

- (Allow users to specify the areas for gardens and tree chopping.) I realise this, I was thinking maybe something along the line of being able to place a special torch at 4 corners of a square to specify a gardens location.

- (Set re-occurring activities, such as have them actually tend the garden instead of just planting.) 
Is this in the most recent 1.7.10 version? as I haven't come across it, but i haven't been looking for it either.

- (Third party weapon support) 
I do see your point with most users, I was aiming more at mod pack creators, allowing them (if they are willing, i know i would be) to add compatibility with other mods in their packs.

- (Leveling system for villagers)
I was thinking maybe number of entities killed, fish caught, crops harvested, with a config determining how much each would affect levels. Maybe a scale in health, or extra attack damage, chop wood faster, something like that. Mostly interested in the health for servers that are tuned to be harder, so that the guards can remain a functional part of the gameplay.

**Comment by Chase62** [comment]
I have another suggestion, I was wondering if you could add last names in a future update, that way it is easier to track families and eventually generations if you play that long. Also have it as an option, where if you marry two villagers then the female's last name changes.

**Comment by moinecraftperv** [comment]
you should also make inbreeding possible in case a siege happened and your children are the only survivors

**Comment by AngleWyrm** [comment]
AtomicStryker's Minions mod does a great job of digging a mineshaft, strip mining wherever the player wants, and performing some other tasks as well. Check it out for functionality:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1280951-1-8-minecraft-minions-evil-always-finds-a-way

**Comment by Candlemancer** [comment]
> (Third party weapon support)
Since item IDs no longer exist, I do not know of a feasible way of doing this. Users will never figure out the appropriate names for items.

I'm not sure if this is easily implemented, but could you maybe add an extra weapon slot in villager's inventories? Just like how MCA 4.x had armor slots for equipping armor, we could have a melee weapon and a ranged weapon slot, and the villager just tries to use the melee weapon like they would a sword and the ranged like they would a bow.

**Comment by Egamer25** [comment]
I have a suggestion for a new item,  A locked/security/family only door to place on your house so other villagers don't randomly wander in and out of your house.  I don't know if this is possible but it's something I would use regularly.

**Comment by moinecraftperv** [comment]
Use an iron door and button for your house ^

**Comment by Egamer25** [comment]
But then my family is locked out/in too.

**Comment by moinecraftperv** [comment]
theres no danger in that because skeletons/zombies dont spawn during the day(will die if they do)
creepers avoid villagers (wildbamaboy said this was intended) and all you hav to do is set their home point in the house, they will automatically tp there at night

**Comment by WildBamaBoy** [comment]
#712
