### ISSUE TITLE
Villager spawn cap.

### ISSUE THREAD

**Issue by DPxKnightxZero** [WildBamaBoy/minecraft-comes-alive#301]
I had like 50 villagers outside my front door once. It was horrible. I had to murder them all. To stop the lag. I mainly installed this so I could marry my fiancee in game. I could care less about npcs. ALSO STAY ON 1.7.10 because 1.8 is still buggy and you haven't even fixed certain defects in the current version!

**Comment by AngleWyrm** [comment]
I would also like the option to disable the creation of guards, as they tend to swarm the place and I'm almost always asleep at night anyway. Can we get a config option for population cap, maybe separated into civilian and guard?

**Comment by DPxKnightxZero** [comment]
Angle that is a brilliant point!

**Comment by SNDGIRL** [comment]
I would go with the previous update until they get this one fixed mainly because it looks like their is a few bugs. Also the guards aren't much help for me they don't attack anything and they get stuck in fences

**Comment by WildBamaBoy** [comment]
@AngleWyrm Guards can be disabled in the mod's configuration. Villager cap will be considered.

**Comment by DPxKnightxZero** [comment]
Pm me when you add a spawn cap when npcs are made by players Ie having kids.

**Comment by DPxKnightxZero** [comment]
Oh yeah it has to be for 1.7.10 there are too many evils - in 1.8

**Comment by DPxKnightxZero** [comment]
https://github.com/ProjectZulu/JustAnotherSpawner/issues/127

**Comment by DPxKnightxZero** [comment]
(Why is talent wasted on the stubborn)

**Comment by WildBamaBoy** [comment]
Protip: Being an asshole doesn't get something done faster.

If your problem is villagers reproducing too quickly, turn off story progression in MCA's config or increase the story progression threshold. Otherwise if villagers are spawning via some other means, it's not my problem. MCA villagers *only* spawn in villages.

**Comment by DPxKnightxZero** [comment]
Okay since you aren't getting it let me explain in the simplest possible way
* I don't care how quickly a villager produces. (Not an issue)
* You should make sure your mod can be mod safe or else you limit the uses to your mod because it is not that awesome by itself.
* The mod needs to have a max MCA npc spawn per chunk.

What a max spawn per chunk does (Since your not putting two and two together.)

*Prevents a single chunk from creating mass lag
*Prevents a server from have mass performance issues because it is handling too many entities.
*Prevents out of memory error caused by too many npcs spawning
*Gives player ability to make sure that the npc count doesn't overwhelm game-play

Why reproduction speed is only a bandaid not a fix
*Some people like npcs poping out of the walls but don't want performance issues
*Some people just want to use the mod to marry other players
*Some people would like to village size specific cap for realism. 4 houses single chunk = 14 max population

Why you haven't understood the reason behind such a feature is beyond me. I figured you were smart but maybe you have a God pc with 12 cores or something and never suffer a fate of performance issues. Maybe you don't use other mods like lycanites at the same time or maybe you just don't care. I am trying to assist growth of your mod. I am sure its not hard to implement for skilled modders. Your mod is problamtic to any mod that adds more npcs because even with JAS and Peaceful surface your mod suffocates gameplay because npcs spawns are handled poorly. I am done talking if you don't get it your not worth my effort.

**Comment by WildBamaBoy** [comment]
Your hostility towards me is unwarranted and *really* doesn't make me want to help you. I'm sorry, but I still don't understand where you're coming from. You're speaking as if MCA villagers are spawning all over your world ("popping out of the walls?") and reproducing without any limits.

They only spawn in villages where original villagers would spawn, and will produce from 1 - 3 children. Using the statistics you've provided (4 houses, assuming two villagers per house), you can end up with 20 villagers at maximum, 12 at minimum from that select group. It's a little lower if they spawn in the houses naturally. Going forward, this group of villagers still isn't going to be a problem.

In the case that a mod adds villagers, they must explicitly assign a new profession ID to their villager, as MCA will overwrite any villager whose profession ID is 0 - 4. If they do not do so, sorry, that's not my problem.

Regarding that, you can turn off this functionality in the config by disabling "Overwrite original villagers". This is also in place for those who just want to use MCA's features with other players.

As I've said above, a cap is being considered which is why this issue remains open. I haven't been given a good reason to *not* implement this, nor can I think of one, so exactly what are you still arguing about?

**Comment by DPxKnightxZero** [comment]
yes they pop out of any house spawned by zelda sword skills or any instant house mod.

**Comment by WildBamaBoy** [comment]
Probably because that mod intends to spawn regular villagers in those houses. I don't know - I don't use them.

MCA is designed to overwrite all *original* villagers unless it's specified that you do not want that to happen in the config. If they're spawning their own villagers and MCA ends up overwriting them, like I said above it's not my problem.

In this sense, I don't believe you would benefit from a spawn cap. Depending on the direction I would decide to take, you'd either end up with villagers missing from these generated houses or the sudden appearance of Minecraft's original villagers. I really wouldn't want to forbid villagers spawning in any sense so it's likely that the latter would be the solution, which doesn't really solve your issue with too many NPCs.

Your problem is irrelevant to MCA. It instead sounds like the use of too many mods that add NPCs and/or villagers. Remove some, disable overwriting villagers in MCA, or remove MCA until the spawn cap is implemented.

**Comment by WildBamaBoy** [comment]
Note to self, quoting someone is a good idea, lest you end up arguing with yourself. -.-

**Comment by moinecraftperv** [comment]
Yeah sometimes in my village theres about 9 villagers and the next few REAL hours theres like 20 and they're guards and villagers who aren't from story progression. Newly spawned villagers sometimes get stuck behind cobble walls
