### ISSUE TITLE
Whistle brings up menu to select specific family members to call.

### ISSUE THREAD

**Issue by WildBamaBoy** [WildBamaBoy/minecraft-comes-alive#319]

**Comment by Orange1861** [comment]
Yeah! MCA needs this. :)

**Comment by TheShootingStar45** [comment]
Wow, useful idea! =D

**Comment by TheShootingStar45** [comment]
Possible Family Update?

Idea for future update:
----------------------------

**Add an icon**, like Parent / Marriage / Available Gifts Information, (The texture is up to you), and when hovered it shows its relation to the player.
**Re-add more parser** (Family Relationship), (This may take time and work, but it'll pay the effort!), and **family dialogue**. *1st Example*, like after you set a villager as your family using relative document (Is Planned) or naturally, their dialogue will change.

*2nd Example*: Your cousin Lillia, their dialogue will change to: **Lilia the Child: You are the funniest in the family!** instead of **Lillia the Child: Your jokes are just too funny!** (seem like different, a family talk and a friend talk).

Finally, **Add an option**, "I have a *big* family", spawning a schematic ( A large house that fits up for a big family), and spawns a big family (after that you can choose what family type that you want, like **Higher Family Lineage**, causing there will be a family lineage above you and equal with you, ex. your spouse, your father and mother, your brother/sister, your *in-laws*, your cousins, uncle/aunt, and your grandparents. The second one is **Lower Family Lineage**, causing there will be a family lineage under you, and equals with you, ex. your spouse, your brother/sister, your *in-laws*, your children, your niece/nephews, and if you want your children to be instant-adult, plus your grandchildren. And if you want both, select **Both**.

That's all of it. Thank you for reading.
Sincerely,
-TheShootingStar45

**Comment by gyser8** [comment]
Perfect idea, WildBamaBoy! c:
