### ISSUE TITLE
Missing or Old Professions??

### ISSUE THREAD

**Issue by Hernan0708** [WildBamaBoy/minecraft-comes-alive#435]
When i was looking in MCA's Files (The .JAR) i looked into en_US.lang i found two unused Professions. (btw i changed en_US.lang to en_US.txt)

##############
# Professions
##############################
profession.archer=Archer
profession.armorer=Armorer
profession.butcher=Butcher
profession.cleric=Cleric
profession.farmer=Farmer
profession.fisherman=Fisherman
profession.fletcher=Fletcher
profession.guard=Guard
profession.spouse=Spouse
profession.leatherworker=Leatherworker
profession.librarian=Librarian
profession.shepherd=Shepherd
profession.toolsmith=Toolsmith
profession.weaponsmith=Weaponsmith
profession.miner=Miner
profession.mason=Mason
profession.baker=Baker
profession.child=Child
profession.househusband=Househusband <-------------------- Here
profession.housewife=Housewife             <------------------------- Here

################

Are these two in the code? is it ok if you implement these two Professions into MCA? if not its ok, i can do it myself for my MCA.

-Hernan0708

**Comment by TheShootingStar45** [comment]
Yes, it is not obtainable from the villager editor, and all of the villagers that naturally spawned didn't have all of those profession. Still waiting for other's answer. (Maybe)  those professions maybe isn't available at MCA, that villagers can have multiple profession at a time, depending is he/she is married or not.
Example, like Diana, a female librarian, married to Richard. Because Diana is married, Diana would has two professions, Housewife and Librarian, but her profession title is Librarian as usual. The Housewife profession that making Diana got married to Richard, and can have  children with Richard.
PS: sorry if i was wrong, but i still waiting from your answer.
      Notify me if that was wrong.
-TheShootingStar45

**Comment by Hernan0708** [comment]
i studied the en_lang.txt and MCA and you sir are right! but i think wildbamaboy should make your spouse's profession say Housewife or HouseHusband and could be an option?!

**Comment by Hernan0708** [comment]
*en_US.lang

**Comment by TheShootingStar45** [comment]
That would be great, also if they would make the spouse title like Husband/Wife...

**Comment by WildBamaBoy** [comment]
Old profession, ignore.
