### ISSUE TITLE
Missing options

### ISSUE THREAD

**Issue by traceguy** [WildBamaBoy/minecraft-comes-alive#473]
Suddenly My Wife is missing half her options.
All I got is
  [Interact]
  [Trade]
  [Special]
  [Procreate]
  [Inventory]

NO FOLLOW  D-:

**Comment by WildBamaBoy** [comment]
Minecraft version, MCA version.

**Comment by traceguy** [comment]
1.7.10
Latest MCA for 1.7.10

This also happens for fiancees. I am pretending with normal villagers for now

**Comment by Hernan0708** [comment]
if i were you i'd post a picture or snapshot for proof.

**Comment by TheAwesomeGem** [comment]
It happens sometimes with my child. After I relog, it is all fine.

**Comment by traceguy** [comment]
I restarted the server it's been several days. Only non related villagers will work

**Comment by TheAwesomeGem** [comment]
I can confirm this issue randomly occurring and most of the times, it can be fixed by doing a relog but sometimes it will never work and we have to end up killing those glitched villagers. It occurs in child too. I host a server with 16 friends and most of them had this issue at one point and sometimes more than once.

**Comment by traceguy** [comment]
@TheAwesomeGem 

If it's a spouse, try giving them divorcee papers before killing them. That brought back the options for me, however they will immediately vanish is you engage/marry

**Comment by WildBamaBoy** [comment]
Now globally known issue, taking a look but closing this issue.
