### ISSUE TITLE
Wife and Kid limited options

### ISSUE THREAD

**Issue by rangersjosh** [WildBamaBoy/minecraft-comes-alive#486]
When I married my wife all the options went away and I could only interact and procreate. And when my kid was grown to the age of 4 I literally only had the option to interact. This is bad because I cant set home, make him do chores, or anything. My wife is just in my house and I cant get her to set home or follow me. Please help!!

**Comment by TheShootingStar45** [comment]
Did you change your username/profile? Villagers can recognize you by your UUID. Marriages between villagers and players can affect what you can interact with that player's spouse. You can't ask them to follow, because due to their marriage, you can't control them. Any idea what's going on now? Hope will be reviewed soon.

**Comment by TheAwesomeGem** [comment]
Seems like a lot of people are having this issue including me. I also noticed that sometimes, I wouldn't have my skin. Not sure if it's cause by this mod or some other mod.

**Comment by WildBamaBoy** [comment]
Haven't heard reports of this in awhile, if it continues to happen on the latest versions come back.
