### ISSUE TITLE
Increase romantic interaction success chance

### ISSUE THREAD

**Issue by moinecraftperv** [WildBamaBoy/minecraft-comes-alive#517]

**Comment by TheShootingStar45** [comment]
**Nice idea**, **romantic success chance will stay longer**. And,
I've got a point.

---
**How about if MCA adds one and only special ability to player, causes them to have more success chance at interacting to specific interaction?**
- *Charming / Charismatic*, will have more success chance at **Chatting**, adds more hearts, comfort villagers along with nice words and conversations.
- *Famous Comedian*, will have more success chance at **Joking**, adds more hearts, surround villagers with laughs and great jokes.
- *Meeters & Greeters*, will have more success chance at **Shaking Hand**, adds more hearts, warm villagers' hearts with nice grips and greater handshakes.
- *Greater Storytellers* will have more success chance at **Telling Stories**, adds more hearts, grab villagers' attention with nice and interesting stories.
- *Even More Flirty* will have more success chance at **Flirting**, adds more hearts, shoot villagers' hearts with love arrows and even more flirty flirts.
- *A Beloved Person*, will have more success chance at **Hugging**, adds more hearts, warm villagers' hearts with warmer hugs.
- *Best Kissers*, will have more success chance at **Kissing**, adds more hearts, turn any villagers' hearts into ice with best and unforgotten kisses.

And the **best of the better of the good** ability, is:
- *The World Is Here, Just For You*, got when you reach a streak of **one hundred** golden hearts, where any ability combined into one, any accident or negative response seldomly affect to relationships, villagers will have an even more longer distance to love you, and will know you will always there.

---

**Comment by HillustratedMike36** [comment]
@TheShootingStar45 Words cannot describe how beautiful your presentation was.

**Comment by TheShootingStar45** [comment]
@HillustratedMike36 
Yes, but MCA need something that is powerful enough to fill what is in need in the game. Any idea?
But if you want to discuss with me, so i'll use my special fancy words. XD

**Comment by TheShootingStar45** [comment]
Dear Michael Hill,

1. Politeness

         Please use nice words and think twice before commenting. Any
offensive language or kind of insults will be removed immediately due to
keep the discussion fun and tidy.

2. Creativity

        Please do not copy other's comment like @HillustratedMike36, and
make your new comment to explain something new.

3. What's the point?

      Please make a clear point what problem did you notice. In your
opinion, words can't. But you can't force. Then what do you want? You did
not explain clearly what do you want.

4. See what's going on

      Please, try to listen. This is an idea, not a presentation. This is
using nice words, not images. This is inspiring, not beautiful. This is my
opinion, not yours. This can improve, not overpowering. Now, try to
understand these words.

Get it? This is serious. Very serious. These words are very pressing. For
the last time, i warned you to do something better. More useful. More
inspiring. Rather than making trouble. Chaos. Fight.

Understand these words. Yeah, do you hear me. These words are pressing.
Pressing. VERY PRESSING.

**Comment by moinecraftperv** [comment]
???
