### ISSUE TITLE
[BUG] Crystalline ball added every single load in SSP

### ISSUE THREAD

**Issue by hron84** [WildBamaBoy/minecraft-comes-alive#535]
I do not know it is intentional or not, but every time I log in into my world, I get this crystalline stuff. Please do not do this.

MCA 5.0.7.2

**Comment by WildBamaBoy** [comment]
Use it to set up the mod, and it'll go away.

**Comment by hron84** [comment]
@WildBamaBoy and what if I wouldn't like to do it? I think it is a wrong way to force me to setup the mod, even if I'm not interested in it.

**Comment by WildBamaBoy** [comment]
If you want to use the mod at all, you need to set it up. If you're not interested in MCA, remove it.

**Comment by hron84** [comment]
@WildBamaBoy I cannot remove it since it is a modpack. Even if the modpack itself can survive the removal, the next update will place it back. Another solution is needed.

**Comment by WildBamaBoy** [comment]
Not really my problem, use a different modpack without MCA. The crystal ball feature will not be removed as it allows the player to choose where their home/village will be when starting out.

(Seriously, just use it once and you'll never have to see it again, I promise)

**Comment by hron84** [comment]
@WildBamaBoy Seriously, you said I have to use another modpack just because MCA does not handle correctly if I do not want to set it up at all (spams player with crystal ball every single world loading)? I do not really want to hurt you but this argument should not and would not be valid. Adding a crystal ball to player inventory every single world load is definitelly your problem since - as the GitHub owner field says - you are the developer of this mod. I cannot change what mods are included in the modpack I chosen to play (especially if the modpack is not authored by me) - all I can do is reporting problems with it to developers.  

All I can ask is consider to not spam player with crystalline ball. At first world load player already got a chance to set up the mod. If he/she loads his/her world a thousand times but do not setup the mod then you should honor this decision. Make a way to collect crystal ball in other way - but do not spam the player. It is not a nice thing. I go further: there is no other mod that does this thing because it is not welcomed right.

**Comment by WildBamaBoy** [comment]
And like you, I will not change something just because you don't like how it works. You can play the modpack how you want, but do not clutter up the issues page with complaints about intended features of a mod you're not even playing, even when I've explained why the feature will not be removed or changed. 

If you have a suggestion for an alternative other than "do it some other way", I'm all ears. Otherwise use the crystal ball or disable it in MCA's config.

**Comment by hron84** [comment]
I hear first there is a way to disable it in the config. I'd like to hear more about it. It would be a more polite solution than throwing out a complete modpack.

About other way: why you do not make it craftable (possibly from that rose gold and some gem)?

**Comment by WildBamaBoy** [comment]
Go to Main Menu->Mods->Minecraft Comes Alive->Config->Give Crystal Ball, and set it to false. I don't like recommending this as people tend to forget they've changed the setting thus MCA may not work properly for them.

The item cannot be made craftable as it's not outwardly obvious what the player must do in order to configure and use the mod properly. That's bad design, and no one reads guides. I'd have hundreds of complaints about "x isn't working correctly" as opposed to the occasional "remove the crystal ball, I don't like it."

**Comment by hron84** [comment]
@WildBamaBoy Thanks. Another question: this setup process is same that builds a house around you at the end of it?

**Comment by WildBamaBoy** [comment]
If you want it to, yes. It also handles establishing the player's name, in-game gender, preferred mate gender, etc. We will be building upon its use later as more features are added so that players can further customize their experience.

**Comment by hron84** [comment]
@WildBamaBoy umm... then there is a weirdness. I tried to scan an enchantment table with a Thaumcraft Thaumometer (basically, I did a long sneaky right click on the table) and suddenly I initiated the setup process. However, it did not asked me to spawn a house around me or not just did it - removing the half of my base and make a lot of item to spawn around me from my chests. I know this is an another issue, so please see #534 I just detailed the problem a bit.

**Comment by Orange1861** [comment]
Just use the crystal ball it will take you under 1 minute.
