### ISSUE TITLE
Rosegold apple ?

### ISSUE THREAD

**Issue by wi-ta** [WildBamaBoy/minecraft-comes-alive#570]
Hi
Golden apple can heal infected villager.
It would be nice if we can use the rosegold to craft a golden apple (maybe rosegold apple).

btw
I have now 79 block rosegold with no use :-)

**Comment by HillustratedMike36** [comment]
First of all, suggestions are a last priority to WildBamaBoy since this is a section for BUG/ISSUES, but I like your suggestion--if vanilla gold-apples can have their effects (Absorption, Regeneration II) and rosegold apples are like enchanted gold apples, and do not require the weakness effect, which can be transitioned similar to the "Procreate" function...

Second: You can't place those blocks, or are you telling that you have 79?

**Comment by wi-ta** [comment]
I have 138 blocks now. ;-)
Sadly with no further use than the 2 rings I did make,
and this is somehow an issue.
Sure I can place them somewhere in the world but that .....
More use as a gift or jewellery for my wife would be nice.

**Comment by WildBamaBoy** [comment]
Rose gold apples will not be a new item - you can turn Rose gold into normal gold and make apples that way. :)
