### ISSUE TITLE
MCA Unable to open the playerdata file for the mod in the worlds/playerdata-mca folder

### ISSUE THREAD

**Issue by Jayfeather311** [WildBamaBoy/minecraft-comes-alive#577]
I have tried opening the playerdata file for this mod with NBT explorer, but it cannot read the file. What is the fix for this?

**Comment by mezzodrinker** [comment]
Which `playerdata` file are you talking about? Is it contained in `.minecraft/saves/<world name>/playerdata` or in `.minecraft/saves/<world name>/playerdata-mca`? Because I have no recollection of any statement that says that files in the latter folder can be opened with an "NBT explorer" (whatever that might be).

**Comment by Jayfeather311** [comment]
The latter one. Its a .dat file which usually can be read by NBT Explorer, its is an NBT editor which can read normal player data and the region files for a world.

**Comment by mezzodrinker** [comment]
So nobody told you that this would work for MCA's .dat files as well, right? How do you come to the conclusion that it would? Just because a file has the same extension as another one doesn't mean their formats have to be the same, let alone match the "designated" format at all. You could, for example, change the extension of a `.txt` file to `.mp3`. Your media player wouldn't be able to handle that, either.

**Comment by Jayfeather311** [comment]
So then how would you propose that I am to open this file then? Huh?

**Comment by WildBamaBoy** [comment]
You don't.
