### ISSUE TITLE
mca skins not working

### ISSUE THREAD

**Issue by Mablegurl** [WildBamaBoy/minecraft-comes-alive#613]
My downloaded mca skins are not working...75% of them are not working. they look all mixed up there body isn't shaped right  can some one please give me advise...im getting my skin from Skindex

**Comment by mezzodrinker** [comment]
* Are you sure you named them correctly?
* Did you add sleeping versions of the skin to the subfolder `sleeping`?
* Are you sure the size of the skins is **exactly** the same as the default skins?
* What do you mean by "they look all mixed up there"? If you mean their clothes are wrong, that is because MCA treats the complete (!) body part of each skin as "clothes" that other villagers can wear as well.

**Comment by Mablegurl** [comment]
yes

**Comment by Mablegurl** [comment]
what i mean is there face is on top of there heads and there is no legs ill
check the sleeping

**Comment by WildBamaBoy** [comment]
Make sure they are in the Steve format, not the Alex format.

**Comment by Hunterballard** [comment]
Hi, I have a similar problem. I download a skin off skindex then edit the same one to be sleeping. Rename the 2 (ex bakerf14) then put one into my textures with the other skins and the other into the sleeping folder. They always end up looking all jumbled. I tried searching 64x32 skins on skindex and put the one I found in Minecraft but the same thing happens. Can someone help me, please?
