### ISSUE TITLE
GUI Issues- Please Help

### ISSUE THREAD

**Issue by Colocon16** [WildBamaBoy/minecraft-comes-alive#631]
When interacting with a villager, a couple textures with the GUI are missing such as the hearts, the rings (Married villagers), age (for children), and possibly others that i also lack. How do I fix this?

**Comment by Febilian** [comment]
I'd like to chime in, I'm playing on a server and I can't tell if a villager is married or not. I apparently got an achievement for getting to five gold hearts with a villager, but trying to marry them resulted in them telling me they were already married - but I had no way of knowing that, because the GUI elements regarding relationship and marriage were missing.

**Comment by Colocon16** [comment]
![2016-02-20_18 16 06](https://cloud.githubusercontent.com/assets/17224592/13200461/31cf42fe-d7fe-11e5-88e0-f48d31f338f7.png)
This is what I'm seeing.

**Comment by Colocon16** [comment]
I've even removed all my mods besides MCA and RadixCore, but even then I do not see their GIU images. Is there an easy fix?

**Comment by WildBamaBoy** [comment]
Download: http://minecraft.curseforge.com/projects/radixcore/files/2283147
