### ISSUE TITLE
Crash when guards attack zombies

### ISSUE THREAD

**Issue by chaNcharge** [WildBamaBoy/minecraft-comes-alive#680]
I realized this has been reported several times, yet this has never been fixed. You say it's not related to MCA, however, in every single crash that I've seen around the Minecraft Forge forums and the Minecraft Forums, every single one of these related crashes (and I've seen like 10 of these related crashes around) all had one thing in common: **They ALL have MCA installed** My best guess is, that when a guard attacks a zombie, sometimes, it triggers a crash and complaining about something broken with the EntityAIAttackOnCollide function. Here's the crash: http://pastebin.com/f3BuABkB

The crash also seems to be happening server-side, not on the client itself.

**Comment by WildBamaBoy** [comment]
The crash comes from Mojang's AI, and it's never directly caused by anything from MCA. I haven't ever been able to reproduce it, and I don't believe I've seen any reports of the problem on 1.8+. It may be 1.7.10 specific.

Since there's no trace of MCA in these crash reports, I have nothing at all to go on when attempting to find the problem.

There's literally nothing more I can do about it.
