### ISSUE TITLE
[Suggestion] Starting Village Variety

### ISSUE THREAD

**Issue by AngleWyrm** [WildBamaBoy/minecraft-comes-alive#693]
Would it be a worthwhile investment of time and effort to create multiple starting villages?
Or a mechanism to allow players to do so?

**Comment by WildBamaBoy** [comment]
Sure, I can add them easily if someone wants to build them. A mechanism for adding them manually, though, not so much.

**Comment by Awkanic** [comment]
It'd be kind of cool if we could leverage the MCEdit schematics files. That would provide a convenient import/export mechanism... just a thought.

**Comment by MentalMouse** [comment]
IIRC, the MCEdit schematics don't allow for adaptation to terrain.  The Ruins format does have some ability for that.

**Comment by AngleWyrm** [comment]
What would be a good recommended minimum and maximum size for a starting village floor plan?
Working on a 4x4 chunk zone in a superflat world at the moment.

**Comment by EnderiumSmith** [comment]
@WildBamaBoy why cant you initiate a vanilla village? it would adapt to terrain and be random. does anything limit it to being created at worldgen?

**Comment by MentalMouse** [comment]
Well, the vanilla village's idea of "adapt to terrain" can leave something to be desired.  Take a look at some of the villages that spawned over ravines, water, or uneven terrain for examples (especially when they extended over the border to a bumpier biome).   I've seen some especially spectacularly broken villages in Abyssalcraft's Darkland Highlands -- I think that moddev has since disabled villages the Highlands, but I got another groaner when a desert village extended into "ordinary" Darklands.

**Comment by EnderiumSmith** [comment]
still better than flat plane that overrides everything.

**Comment by hron84** [comment]
OTG has some nice way to create custom villages with very custom structures. Maybe it worth to take a look.
