### ISSUE TITLE
A Crash - Hope it helps - now with video proof!

### ISSUE THREAD

**Issue by DPxKnightxZero** [WildBamaBoy/minecraft-comes-alive#768]
https://gist.github.com/DPxKnightxZero/fb21be50748edac4accfb990498a8729

Since I am reporting this for a friend I am not going to spend a ton of time detailing issues if she wants to she can.

Oh and a crash video 
https://youtu.be/J8i-O6JMOGI

**Comment by WildBamaBoy** [comment]
You'll need to reproduce the issue with just MCA and RadixCore installed.

**Comment by bloodmc** [comment]
@WildBamaBoy My server just crashed from same exact issue posted above.

http://pastebin.com/raw/rqtYBDqp

The issue seems to be here

https://github.com/WildBamaBoy/minecraft-comes-alive/blob/master/src/main/java/mca/packets/PacketMemorialUpdateGet.java#L57

This needs to make sure 'memorial' is not null before attempting to create a packet.
