### ISSUE TITLE
Npc's are invisible.

### ISSUE THREAD

**Issue by lukehemstreet** [WildBamaBoy/minecraft-comes-alive#783]
- [] I am running the latest mod versions of MCA and RadixCore.
- [] I can reproduce this issue with just MCA and RadixCore installed.
- [] I can provide my Minecraft version and MCA version.
- [] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## I haven't been able to see the NPC's body, but i can see their shadow. PLZ help!

common issue i found in every world not know why it is happening.

**Comment by AzureDreams1** [comment]
I'm not 100% on this but I get the same issue. I run with a few other mods but it shouldn't cause this... I seem to be able to interact with all the villagers just fine and everything... that is until I leave the village for more than 16 in game hours which is like 16 minutes or something. But if they are outside my render distance (at 8 because my laptop is carp) then they disapear. They seem to be replaced with invisible versions of other villagers because there didn't use to be a fisherman in my village and when I came back there was an invisible fisherman in the library. And none of them can move. I tried reloading the world  by exiting the world only to the main menu and now all the invisible people are gone too. Just poof. I now only have 1 guard that just happened to still be following me.

**Comment by AzureDreams1** [comment]
I'm not sure which setting fixed it but I made sure that settings were as so:

In game config gui:
Minecraft Forge>config>general settings>remove erroring entities: false (same for tile entities)

Minecraft Comes Alive>config>Overwrite original villagers: true (default)

Minecraft Comes Alive>config>replenish empty villages:false

These helped me so maybe they'll help you.

**Comment by WildBamaBoy** [comment]
You've got to try with just MCA and RadixCore installed, otherwise I can't be sure it's not caused by another mod.

**Comment by manusoftar** [comment]
I having the same behaviour and im only using MCA... here are some captures of what i see.

![2018-11-04_00 15 55](https://user-images.githubusercontent.com/6219523/47959605-04fd5f80-dfc7-11e8-81b6-9316bb1f301e.png)
![2018-11-04_00 15 59](https://user-images.githubusercontent.com/6219523/47959606-04fd5f80-dfc7-11e8-9cd9-9a5f0394081f.png)

Im running Minecraft Forge 1.12.2-14.23.5.2770, MCA 1.12.x-5.3.1 and RadixCore-1.12.x-2.2.1

Please fix this issue, i saw a NullPointerException on the log, i guess there is something wrong with the textures.
