### ISSUE TITLE
Language right locally - Wrong on Server

### ISSUE THREAD

**Issue by TheRealDadbeard** [WildBamaBoy/minecraft-comes-alive#802]
- [x] I am running the latest mod versions of MCA and RadixCore.
- [x] I can reproduce this issue with just MCA and RadixCore installed.
- [x] I can provide my Minecraft version and MCA version.
- [x] I have searched for the issue previously and it was either not previously reported, or previously fixed and I'm having the same problem.
- [] I am crashing and can provide my crash report.

## Versions
Minecraft 1.10.2
MCA 5.2.3

## Issue Description
The Language for Villagers in the Chatbox is wrong. I'm located in Germany, like the Server but somehow it always loads the English Textfiles. Buttons in the interaction menu are fine. Workauround for now is to replace English locale with the German one.

Using the mod locally gives me no issues as seen in screenshot.
![2016-11-10_02 37 48](https://cloud.githubusercontent.com/assets/23340600/20161470/f5f5d6d8-a6ee-11e6-8813-71cde9f0a014.png)

And this is on the server, where the chat is wrong.
![2016-11-10_02 38 49](https://cloud.githubusercontent.com/assets/23340600/20161481/076ae2b4-a6ef-11e6-9d00-75beb04778a9.png)

## Reproduce Steps
Just use the mod server side with another local language as english. For me this is German.

**Comment by DarthJimbo** [comment]
Seconded. Got the same issue on my server. The chat language seems to be fixed to english. If I swap the english with for instance the german language file on server side (as mentioned above), then the villagers are chatting german. But now english users are screwed, because the villagers always talk german. 
However, I think there is no real possibility, maybe not even a need to solve this, because you would have to work with dialog ids or something, so that dialogs get synchronized. In this case it would be too difficult to setup own dialogs, because you would have to fiddle around with these IDs and translations and get them to the client and so on. In my opinion the servers admin should decide, which language the villagers are using. Maybe there should be a server side option or command to set the language, rather than fiddling with the jar-file.
Greetings
Darth_Jimbo

**Comment by WildBamaBoy** [comment]
Solution will be to ensure the server sends only phrase IDs to all clients rather than translated phrases, and those phrase IDs will be translated into the client's language.

**Comment by WildBamaBoy** [comment]
In the recent update you may now select the language that the server will run in MCA's configuration file.

**Comment by TheRealDadbeard** [comment]
I am on 1.10.2, not fixed there. Will this be backported??

**Comment by WildBamaBoy** [comment]
No, 1.10.2 is no longer supported.
