### ISSUE TITLE
Kids dying (and I still can't figure out why) But not dropping chests with toys to revive them!

### ISSUE THREAD

**Issue by Lyrina25** [WildBamaBoy/minecraft-comes-alive#863]
Exactly as my title say. I've had two kids die in my underground fillage and I've taken out every place they could have jumped up to and suffocated in...

**Comment by ghost** [comment]
Lyrina25 you should specify the version of the mod for example 5.1.2 or 5.2.2 and the version of minecraft in which you are 1.7.10 or 1.10.2 so that the creators of the mod can identify the problem and solve it we must remember that although they Put these features will not always work correctly apart may be that if you use mods with more reason fails, for example if you use mods that appear tombs when they die you should enter the configuration of the mod in the folder config of the .minecraft folder and deactivate that aparescan tombs When the villagers die as the tomb could be generated in the place of the chest where the things of your son should be either in turn or also "crash" the game

Translate with google excuse the errors if there are

**Comment by WildBamaBoy** [comment]
If a chest is generated it will appear in your server log/game log. Check that for a phrase like "generated memorial chest at", and it will tell you where it was generated.
