### ISSUE TITLE
[BUG?] MCA villager visual glitch

### ISSUE THREAD

**Issue by hron84** [WildBamaBoy/minecraft-comes-alive#873]
Right now I cannot provide a screenshot but last night i experienced an issue with MCA villagers. Some of them just not displaying, even not have a model. The only thing that tells me there is a villager is Neat / WAILA / RPG HUD that displays me the entity name and profession, but I cannot interact with him/her neither can see him/her.
I am not pretty sure but I think I can see a green-ish item on the ground that represents the villager but maybe it's just a decoration, since Sprout (the modpack I play with) uses many different custom structures including village houses. 
I use the latest version of Sprout and I did not tried to update MCA yet (not even checked if there is an update) as I do not want to break my quest progressions.

In the meantime, is there any config option to have vanilla-ish villagers along with MCA ones (I mean tell MCA to not convert all villagers to its own version)?

MC version: 1.10.2
MCA version: ???

**Comment by Catoptrix** [comment]
Hi there
Love this mod. Together with structpro, this mod makes Cities with Citizens, awesome. I have a similar issue but not sure it has to do with MCA. Maybe you guys can help me.

MCA Version: 1.12-5.3.0
Minecraft Version: 1.12.1
Forge Version: 2444

Installed Mods: 
- astralsorcery
- BetterFoliage
- Biomes O plenty
- Birdsfoods
- Chunk Animator
- corail_pillar_extension_biomesoplenty
- corail_pillar
- fastleafdecay
- ivtoolkit-1.3.3-1.12
- jei:1.12-4.7.5.85
- jepb-1-12-1.2.1
- justenoughresources-1.12-0.8.3.23
- minecolonies-1.12.-0.9.3530
- optifine_1.12.1_HD_U_C5
- plants-1.12-1.2.0
- radixcore-1.12-2.2.0
- recurrentcomplex-1.4.5
- structpro-4.0-1.12.1
- teletoro-1.12.1-26
- torohealth-1.12.1-11
- toughasnails-1.12-3.0.0.62

Using 2444 Forge because I want to do a SpongeForge Server and they are using 2444 for there 1.12.1 build. Right now testing for making my own modpack.

The child issue I only had once, when I was using Family in the beginning and my (Trait Odd) child appeared... totally black lol, no texture at all... really odd. After that when I now click Family I have a Wife but no child. That doesn't bother me that much because normally I just click "none of the above" and just fly creative mode to the next town. Now the issue i'm having is that sometimes the models don't get loaded. I realize there are Villagers because they talk to me or my pointer is over them and they get displayed with torohealth. I can though interact with them. 

When I close the world and load the world again, they are displayed totally fine. Now this also happens with Monsters sometimes. They suddenly disappear being invisible (only see them with torohealth) and sometimes reappear with no reason at all, not sure why that is, I hope you guys can have some suggestions.

Best regards

NSP

P.S. I also post this in Forge and Structpro Forums/githubs to get some ideas and update if I get some information.

**Comment by hron84** [comment]
Additional notes to my comment: I did not messed with MCA mechanics, nor created a family, nor have a wife, neither things. And I have to express, some villagers _are_ visible.

**Comment by WildBamaBoy** [comment]
1.10.2 is no longer supported, however this sounds like another mod is causing the problem. I haven't had an issue such as this reported throughout MCA's 1.10.2 run.

As in MCA's terms, troubleshooting of MCA issues within modpacks are the responsibility of the modpack creator, since most of the time any issues are due to conflicts between mods.

If you load up MCA by itself, this problem shouldn't occur.

Also @nspthegreat you are running a supported version, so reproduce your issue with just MCA and RadixCore installed and if the problem still occurs, submit a new issue here.

**Comment by hron84** [comment]
@WildBamaBoy I'm just curious, how other mod can cause villager disappear completely? I can imagine if texture lookup somehow fails (?) but models should load correctly and/or should fall back to default villager model+texture. 

Btw, Sprout decided to drop MCA as it cause a _lot_ of conflicting other mods. While I partially agree your point with modpacks, as a mod developer, you should test your mods with popular mods to ensure you not causing a game-breaking incompatibility and also providing a fallback compatibility if it is needed (e.g. ExtraUtilities2 contract vs MCA villagers). Especially if you decide to _replace_ something in vanilla with your completely custom implementation.

**Comment by WildBamaBoy** [comment]
@hron84 Could be anything really that modifies rendering. The last issue similar to this was caused by the old Damage Indicators mod, where you would look at a villager and suddenly you're seeing _through_ everything.

By replacing vanilla gameplay elements with a custom implementation, you should not expect other mods that modify villagers to work in the same way. MCA's purpose is to entirely replace the villagers, and that's all. 

In modpacks, it should stand on its own and not be used alongside other mods that modify villagers. It takes precautions where needed to avoid overwriting villagers **added** by mods, but if other mods that also **modify** villagers are included and you expect those mods to work properly - _you're gonna have a bad time_.

I maintain that troubleshooting is the responsibility of the modpack creator, and this page exists for them to submit issues once they find the problem. If there's something I can reasonably do about it, I will. 

It's quite unlikely that MCA was causing a lot of conflicts with other mods unless the Sprout creators did exactly what I said you _shouldn't_ do. They did not reach out to me (as far as I am aware) regarding issues with MCA in their pack, so blame them for removing it without attempts to get the problems fixed. ¯\_(ツ)_/¯

**Comment by hron84** [comment]
@WildBamaBoy from another point of view, Sprout creator maybe has a limited time to handle problems and he/she needed to decide if MCA adds enough content to the gaming experience that worth the time to spend hunting problems. I would not blame him/her for this decision. 

> In modpacks, it should stand on its own and not be used alongside other mods that modify villagers. It takes precautions where needed to avoid overwriting villagers added by mods, but if other mods that also modify villagers are included and you expect those mods to work properly - you're gonna have a bad time.

While I accept your opinion, let me slightly disagree. MCA adds a great content to the game but I think a mod should not be picky about what other mods it allow alongside with itself. As far as I know, Minecraft mods are about freedom in the gameplay and adding more fun to the game. If I, for example, have fun with MCA but also would like to have fun with a mod that - in the background - also modifies the villagers, then you should not blame me. 
First, because I - even as a modpack creator or a player - may or may not know how the mod exactly do its thing in the code side. A modpack creator is not necessarily an experienced Java coder. 
Second, because - I think - the most important in this story is the player, nothing else and especially not the developer - sorry about it. If a developer faces with an incompatibility with a very popular mod, he/she should not say "but my mod does not *allow* this" and close the issue but have to be cooperative and take a look how it could be solved. It would greatly improve not only the reputation of the affected developer but the developed mod itself - as it could be available for more players. 

Sorry, if my opinion hurts you, it definitely not my basic intention. However, I think mod developers should respect each other and also should respect modpack creators because they help to spread mods to a wider audience.

**Comment by WildBamaBoy** [comment]
@hron84 You seem to feel as if I completely shut out the idea of compatibility with other mods, that's not true:
> I maintain that troubleshooting is the responsibility of the modpack creator, and this page exists for them to submit issues once they find the problem. _If there's something I can reasonably do about it, I will._

Making **modpacks** is not hard, nor is it very time-consuming. Making **mods** is the complete opposite. As I said before, I do not have the free time, nor do I feel that it is my responsibility, to test MCA alongside _this_ or _that_. Immediately as an issue was noticed in the modpack, the issue should have been reported to the pack creator. This is a responsibility they assume as it is now THEIR product the public uses. The creator should have then located the conflicting mod, which is as simple as removing potential problem mods until the issue goes away, and posted here.

I will also restate - MCA is a total conversion of Minecraft's villagers. Expecting other mods that modify villagers to work properly is illogical. If pack creators cannot see that - they probably shouldn't be trying to make a modpack.

Since MCA has been removed from Sprout, and because I no longer support 1.10.2 due to lack of time to work on mods _(!!!)_, there's nothing that I can do for you.
