### ISSUE TITLE
Villager Job Title to Trade Options and Name to Gender Mismatch

### ISSUE THREAD

**Issue by getsandom** [WildBamaBoy/minecraft-comes-alive#893]
When trading with villagers the job title after their names almost never match the trade options the villager have, It seems the titles are being randomly distributed with no regard to the actual job and the trades that come with it.  Another occurrence is the name of the villagers with regards to the ones that are "male only", as they will occasionally be attributed to female villagers, this is less frequent than the trade mismatch and I have not observed "female only" names attributed to males but it "feels" like it has the same random nature of the trades. The mismatch was observed on a clean installation with only the base game, forge1.12.2-14.23.0.2495, MCA-1.12.x-5.3.1-universal and RadixCore-1.12.x-2.2.1-universal applied.

**Comment by zombieMAX02** [comment]
I have the same problem in my survival world with the same version of MCA.

**Comment by Galindorf** [comment]
Same here, my current mods are: 

 forge1.12.2-14.23.0.2495

BetterFoliage-MC1.12-2.1.10
BiomesOPlenty-1.12.2-7.0.1.2298-universal.jar
chococraft_1.12.1-0.9.1.52.jar
CustomMobSpawner-3.11.3.jar
DrZharks MoCreatures Mod-12.0.3.jar
DynamicSurroundings-1.12.2-3.4.7.2.jar
journeymap-1.12-5.4.9.jar
JustAFewFish-1.7_for_1.12.jar
Mantle-1.12-1.3.1.21.jar
MCA-1.12.x-5.3.1-universal.jar
Natura-1.12-4.3.0.17.jar
PetBat-1.12.jar
RadixCore-1.12.x-2.2.1-universal.jar
SoundFilters-0.10_for_1.12.jar
TreeChopper-1.12.1-1.2.2.jar

Guards in particular seem to spawn with female forms and male names. I mean hey, if the lady wants to be called Brutus I'm not gonna judge since she's defending the village from Manticores but... 

I have a different interesting note, my (real life) husband finally got tired of not being able to marry me (or anyone) or have kids (because of the marriage bug) so he spawned a new villager using an egg and used the Villager Editor to change his job to "Cleric." When I went to trade with the Cleric as a villager, he had no trades at all! The trade screen came up but it was empty. 
Further: One of the naturally spawned MCA Villager children grew up and became a Cleric! ... Who also has an empty trade screen with no trades in it. 
Even further: Because I put them both together in the 'church' that I had made, they got married and had a child. When THIS child grew to adult, his title was "Shepherd" but he has the minecraft Cleric trades. (whoa). 

None of my villagers have title and trades that match; and the majority of them cannot be hired (there is nothing under the "special" menu). This can probably be merged with the "My Children are Do-less" thread....
