### ISSUE TITLE
[Suggestion] Change ring recipe to be cheaper

### ISSUE THREAD

**Issue by PurpleHel** [WildBamaBoy/minecraft-comes-alive#904]
Rings seem extremely expensive, requiring as much gold as a sword, pickaxe, and axe together. I suggest changing the recipes to use gold and rose gold nuggets instead. Lots of mods add gold nuggets, it's pretty common, so wouldn't be some crazy unheard of thing. :)

**Comment by WildBamaBoy** [comment]
Yes, they are expensive since the benefit of using them is so great (children that work for you). Rose gold is intended to be used as the "cheaper" option since you can't really use it for anything else. That frees up your regular gold for use with other mods that make abundant use of it. Plus you can convert rose gold to regular gold as well.
