### ISSUE TITLE
Vanilla villagers in green clothes don't become MCA villagers

### ISSUE THREAD

**Issue by timurall** [WildBamaBoy/minecraft-comes-alive#925]
When I spawn villagers using vanilla spawn egg or install MCA mod over a save with vanilla villagers, the villagers in green clothes added in the 1.8 version don't turn into MCA villagers.
![2017-11-23_22 39 52](https://user-images.githubusercontent.com/33928607/33187354-3f04b73a-d0a2-11e7-9170-07942c14ce06.png)

Minecraft 1.12.2
MCA-1.12.x-5.3.1-universal
PadixCore-1.12.x-2.2.1-universal

P.S. Sorry for spelling and/or grammatical mistakes, English is not my native language and I have some problems with articles

**Comment by Galindorf** [comment]
I think this happens because green-robed villagers aren't "real" villagers, they're "dummy" villagers that have no profession and can't be traded with. I just sort of treat them like the village idiot, which makes them sort of special actually, because they're pretty rare! I named them with name tags, hehe...
